name: battery_optimization_helper
description: A Flutter plugin to disable or request disabling battery optimization on Android.
version: 0.0.5
homepage: https://github.com/thethtwe-dev/battery_optimization_helper
repository: https://github.com/thethtwe-dev/battery_optimization_helper
issue_tracker: https://github.com/thethtwe-dev/battery_optimization_helper/issues

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:

  plugin:
    platforms:
      android:
        package: com.example.battery_optimization_helper
        pluginClass: BatteryOptimizationHelperPlugin
